# -*- coding: utf-8 -*-
"""All_Positive_Numbers.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1q4qIP6sU4JWDa_65JOE0Qy0pabtQKMPJ
"""

list1=[12,-7,5,64,-14]

for i in list1:
  if i<0:
    list1.remove(i)
print(list1)

list2=[12,14,-95,3]

for i in list2:
  if i<0:
    list2.remove(i)
print(list2)