# -*- coding: utf-8 -*-
"""Fibonacci_Series.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YWsBUfKbDw7o0oEt_vSFE_5YRQ_hVUbL
"""

#Fibonacci series

#Taking input
n=int(input("Enter the number of terms :"))

#First two term
n1=0
n2=1

next_term=0

#If the term entered by user is negative or zero
if n<=0:
  print("Fibonacci series doesn't exist for negative numbers.")


#If the term entered by user is first
elif n==1:
  print("Fibonacci series upto 1st term is : ",term1)

#If the user entered more than one terms
else:
  print("Fibonacci series upto",n,"terms is:")
  while next_term<n:
    print(n1)
    nth=n1+n2
    n1=n2
    n2=nth
    next_term+=1